# Generated by Django 4.0.3 on 2022-04-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='queicontent',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.user'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
