# Generated by Django 4.0.4 on 2022-04-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0002_user_alter_queicontent_autor_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queicontent',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='queicontent',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='queicontent',
            name='text_description',
        ),
        migrations.RemoveField(
            model_name='queicontent',
            name='title',
        ),
        migrations.CreateModel(
            name='Quei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_description', models.CharField(default='Not description', max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('category', models.CharField(max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.user')),
            ],
        ),
        migrations.AddField(
            model_name='queicontent',
            name='quei_referece',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doors.quei'),
        ),
    ]
