# Generated by Django 4.0.4 on 2022-05-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0004_user_user_description_alter_quei_text_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./static/images/default-avatar.jpg', upload_to='static'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='Basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='quei',
            name='category',
            field=models.CharField(default='NoCategory', max_length=20),
        ),
    ]
