# Generated by Django 4.0.4 on 2022-05-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0005_user_image_user_level_alter_quei_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
