# Generated by Django 4.0.4 on 2022-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='users'),
        ),
    ]
