# Generated by Django 4.0.4 on 2022-05-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quei',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
