# Generated by Django 4.0.4 on 2022-05-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0008_quei_value_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(default='Not text Content')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='quei',
        ),
        migrations.RenameModel(
            old_name='Quei',
            new_name='Door',
        ),
        migrations.DeleteModel(
            name='QueiContent',
        ),
        migrations.AddField(
            model_name='doorcontent',
            name='door_referece',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doors.door'),
        ),
    ]
