# Generated by Django 4.0.4 on 2022-05-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0009_doorcontent_remove_comment_quei_rename_quei_door_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='door',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doors.doorcontent'),
        ),
    ]
