# Generated by Django 4.0.4 on 2022-05-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0011_door_text_content_door_votes_alter_comment_door_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_Money', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='door',
            name='category',
        ),
        migrations.RemoveField(
            model_name='door',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='door',
            name='value',
        ),
        migrations.RemoveField(
            model_name='door',
            name='votes',
        ),
        migrations.CreateModel(
            name='Quei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('value', models.IntegerField(default=0)),
                ('category', models.CharField(default='NoCategory', max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.door')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doors.wallet'),
        ),
    ]
