# Generated by Django 4.0.4 on 2022-05-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0012_wallet_remove_door_category_remove_door_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
    ]
