# Generated by Django 4.0.4 on 2022-07-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0014_remove_quei_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(default='Not text Content')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Quei',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.RemoveField(
            model_name='door',
            name='text_content',
        ),
        migrations.AddField(
            model_name='door',
            name='category',
            field=models.CharField(default='NoCategory', max_length=20),
        ),
        migrations.AddField(
            model_name='door',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='door',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doorcontent',
            name='door_referece',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doors.door'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='door',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doors.doorcontent'),
        ),
    ]
