# Generated by Django 4.0.4 on 2022-07-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0015_doorcontent_delete_quei_delete_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
